apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

buildMetadata: [managedByLabel]

labels:
- pairs:
    commit: __COMMIT_HASH__
  includeTemplates: true
  includeSelectors: true

images:
- name: chukmunnlee/dov-bear
  newName: chukmunnlee/__NEW_IMAGE_NAME__
  digest: __NEW_DIGEST__
